---
- name: Kill high memory consuming processes on Windows (Actual Kill)
  hosts: win_servers
  gather_facts: no

  vars:
    memory_threshold_mb: 500         # Kill any process using more than this memory
    exclude_names:                   # Processes to NEVER kill
      - "System"
      - "Idle"
      - "svchost"
      - "winlogon"
      - "lsass"
      - "csrss"
      - "services"
      - "wininit"
      - "smss"
      - "explorer"

  tasks:

    - name: Get list of processes with memory usage
    - ansible.windows.win_shell: |
        Get-Process | Select-Object Name,Id,@{Name='WS_MB';Expression={[math]::Round($_.WorkingSet64/1MB,0)}} |
        ConvertTo-Json
      register: proc_list

    - name: Build list of high memory PIDs
      set_fact:
        high_mem_pids: >-
          {{
            proc_list.stdout | from_json
            | selectattr('WS_MB','>', memory_threshold_mb)
            | rejectattr('Name','in', exclude_names)
            | map(attribute='Id')
            | list
          }}

    - name: Show processes that will be killed
      debug:
        msg: "Processes to kill (PIDs): {{ high_mem_pids }}"

    - name: Kill high memory processes
      ansible.windows.win_shell: |
        foreach ($pid in {{ high_mem_pids }}) {
          try {
            Write-Output "Killing PID $pid"
            Stop-Process -Id $pid -Force -ErrorAction Stop
          } catch {
            Write-Output "Failed to kill PID $pid: $($_.Exception.Message)"
          }
        }
      when: high_mem_pids | length > 0
