- name: Kill High Memory Processes Immediate
  hosts: win_servers
  gather_facts: no
  vars:
    process_limit: 5
    what_if_mode: false          # set to false to actually stop processes (this playbook uses false)
    memory_threshold_mb: 200
    kill_retries: 3
    kill_retry_delay: 2
    excluded_processes:
      - "System"
      - "svchost"
      - "csrss"
      - "wininit"
      - "services"
      - "lsass"
      - "winlogon"
      - "explorer"
  tasks:
    - name: Build candidate list with PIDs (use WorkingSet64)
      ansible.windows.win_powershell:
        script: |
          $limit = {{ process_limit }}
          $thresholdBytes = {{ memory_threshold_mb }} * 1MB
          $excluded = @(
            {% for process in excluded_processes %}
            "{{ process }}"{{ "," if not loop.last }}
            {% endfor %}
          )
          $candidates = Get-Process |
            Where-Object { $_.WorkingSet64 -gt $thresholdBytes -and ($excluded -notcontains $_.ProcessName) } |
            Sort-Object -Property WorkingSet64 -Descending |
            Select-Object -First $limit |
            Select-Object ProcessName, Id, @{Name='MemoryMB';Expression={[math]::Round($_.WorkingSet64/1MB,2)}}
          $candidates | ConvertTo-Json -Depth 3
      register: candidates

    - name: Show candidate processes safely
      debug:
        msg: >-
          {{
            (candidates.stdout | default('[]') )
            | from_json
          }}

    - name: Kill each candidate by Id with retries and verification
      ansible.windows.win_powershell:
        script: |
          $whatIf = {{ ' $true' if what_if_mode else ' $false' }}
          $retries = {{ kill_retries }}
          $delay = {{ kill_retry_delay }}
          $candidates = {{ candidates.stdout | default('[]') | to_json }}
          $results = @()
          foreach ($c in $candidates) {
            $id = $c.Id
            $name = $c.ProcessName
            $entry = [ordered]@{ ProcessName = $name; Id = $id; Attempts = 0; Status = 'Pending' }
            $stopped = $false
            for ($i=1; $i -le $retries; $i++) {
              $entry.Attempts = $i
              $proc = Get-Process -Id $id -ErrorAction SilentlyContinue
              if ($null -eq $proc) { $entry.Status = 'NotFound'; $stopped = $true; break }
              if (-not $whatIf) {
                try {
                  Stop-Process -Id $id -Force -ErrorAction Stop
                } catch {
                  $entry.Error = $_.Exception.Message
                }
              } else {
                Stop-Process -Id $id -WhatIf -ErrorAction SilentlyContinue
              }
              Start-Sleep -Seconds $delay
              $proc = Get-Process -Id $id -ErrorAction SilentlyContinue
              if ($null -eq $proc) { $entry.Status = 'Stopped'; $stopped = $true; break }
            }
            if (-not $stopped -and $entry.Status -ne 'Stopped') { $entry.Status = 'StillRunning' }
            $results += $entry
          }
          $results | ConvertTo-Json -Depth 4
      register: kill_result

    - name: Show kill results safely
      debug:
        msg: >-
          {{
            (kill_result.stdout | default('[]'))
            | from_json
          }}

