# Playbook to kill high memory processes on Windows
- name: Kill High Memory Processes
  hosts: win_servers
  gather_facts: no
  vars:
    process_limit: 5
    what_if_mode: true        # set to false to actually stop processes
    excluded_processes:
      - "System"
      - "svchost"
      - "csrss"
      - "wininit"
      - "services"
      - "lsass"
      - "winlogon"
      - "explorer"
  tasks:
    - name: Get and kill high memory processes
      ansible.windows.win_powershell:
        script: |
          $limit = {{ process_limit }}
          $whatIf = {{ ' $true' if what_if_mode else ' $false' }}
          $excluded = @(
            {% for process in excluded_processes %}
            "{{ process }}"{{ "," if not loop.last }}
            {% endfor %}
          )

          # threshold in bytes (example: 200MB). Adjust if needed.
          $threshold = 200MB

          $processes = Get-Process |
            Where-Object { $_.WorkingSet -gt $threshold -and ($excluded -notcontains $_.ProcessName) } |
            Sort-Object -Property WorkingSet -Descending |
            Select-Object -First $limit

          foreach ($proc in $processes) {
            $memMB = [math]::Round($proc.WorkingSet / 1MB, 2)
            Write-Output ("Killing process: {0} (ID: {1}, Memory: {2} MB)" -f $proc.ProcessName, $proc.Id, $memMB)
            if (-not $whatIf) {
              Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
            } else {
              Stop-Process -Id $proc.Id -WhatIf -ErrorAction SilentlyContinue
            }
          }
      register: kill_result

    - name: Display kill results
      debug:
        var: kill_result.output

