---
- name: Kill high CPU processes on Linux
  hosts: lin_servers
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 40   # adjust as needed
    log_file: /var/log/high_cpu_kill.log

  tasks:

    - name: Capture current top CPU processes
      shell: "ps -eo pid,comm,%cpu --sort=-%cpu | head -n 10"
      register: top_processes

    - name: Log current processes before remediation
      blockinfile:
        path: "{{ log_file }}"
        block: |
          === BEFORE === {{ lookup('pipe','date +%Y-%m-%dT%H:%M:%S') }}
          {{ top_processes.stdout }}
        create: yes
      become: yes

    - name: Show raw ps output (debug for AWX)
      debug:
        var: top_processes.stdout

    - name: Find PIDs above threshold
      shell: >
        ps -eo pid,%cpu,comm --no-headers --sort=-%cpu |
        awk '{if ($2+0 > {{ cpu_threshold }}) print $1}'
      register: high_cpu_pids

    - name: Show high CPU PIDs
      debug:
        var: high_cpu_pids.stdout_lines

    - name: Kill high CPU processes by PID
      command: "kill -9 {{ item }}"
      loop: "{{ high_cpu_pids.stdout_lines }}"
      when: high_cpu_pids.stdout_lines | length > 0
      become: yes
      ignore_errors: yes

    - name: Kill stress processes explicitly (fallback)
      shell: "pkill -9 stress || true"
      become: yes

    - name: Capture processes after remediation
      shell: "ps -eo pid,comm,%cpu --sort=-%cpu | head -n 10"
      register: post_processes

    - name: Log processes after remediation
      blockinfile:
        path: "{{ log_file }}"
        block: |
          === AFTER === {{ lookup('pipe','date +%Y-%m-%dT%H:%M:%S') }}
          {{ post_processes.stdout }}
        create: yes
      become: yes

