---
- name: Create Linux user with default password and force change
  hosts: lin_users
  become: yes
  tasks:
    - name: Ensure user exists with default password
      ansible.builtin.user:
        name: demo_user
        comment: "Demo User Account"
        shell: /bin/bash
        home: /home/demo_user
        create_home: yes
        password: "{{ 'MySecurePassword123' | password_hash('sha512') }}"

    - name: Force password change on next login
      ansible.builtin.command: chage -d 0 demo_user

