---
- name: Kill top memory consuming processes on Linux
  hosts: lin_servers
  become: yes
  gather_facts: no

  vars:
    top_n: 5   # Number of processes to kill (highest memory usage)
    log_file: /var/log/high_mem_kill.log

  tasks:

    - name: Capture current top memory processes
      shell: "ps -eo pid,comm,rss --sort=-rss | head -n {{ top_n }}"
      register: top_mem_processes

    - name: Log current processes before remediation
      lineinfile:
        path: "{{ log_file }}"
        line: "=== BEFORE === {{ ansible_date_time.iso8601 }}\n{{ top_mem_processes.stdout }}"
        create: yes
      delegate_to: localhost

    - name: Extract PIDs of top memory processes
      shell: "ps -eo pid --sort=-rss | head -n {{ top_n }}"
      register: top_mem_pids

    - name: Kill top memory consuming processes
      shell: "kill -9 {{ item }}"
      loop: "{{ top_mem_pids.stdout_lines }}"
      when: top_mem_pids.stdout_lines | length > 0

    - name: Capture processes after remediation
      shell: "ps -eo pid,comm,rss --sort=-rss | head -n {{ top_n }}"
      register: post_mem_processes

    - name: Log processes after remediation
      lineinfile:
        path: "{{ log_file }}"
        line: "=== AFTER === {{ ansible_date_time.iso8601 }}\n{{ post_mem_processes.stdout }}"
        create: yes
      delegate_to: localhost

